export interface PostIncidentReport{
    incidentDate: moment.Moment,
    licensePlate: string,
    driverFirstName: string,
    driverLastName: string,
    driverAge: number,
    driverLicense: string,
    driverCountry: string,
    driverCity: string,
    driverZipCode: string,
    driverStreet: string,
    driverPhoneNumber: string,
    driverEmail: string,
    incidentSummary: string,
    towingNeeded: string,
    accidentCity: string,
    accidentZipCode: string,
    accidentAddress: string,
}